url:
  u12306: 'https://kyfw.12306.cn'
  u2: 'http://www.sina.com'

api:
  - id: 'station_name'
    name: '车站'
    url: '{u12306}/otn/resources/js/framework/station_name.js'
    get: 'station_version=1.9137'